spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Eh3LG5cv50g6FJmlymimYNKakWXkMyBB159cAdhu76glE1bxSIErD6wyDQP9Q+0Cc6oKiAA7FZKJc2MY7iJk8g==
    url: jdbc:mysql://127.0.0.1:3306/bzfx?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL= false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://59.110.172.20:33060/bzfx?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL= false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://bzfx_db/bzfx?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL= false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        stat:
          enabled: true
        slf4j:
          enabled: true
        wall:
          enabled: true
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAPP/l5GjEJMYPbrWrtO5bz9tbrqlTw1t/wn5OWmGtOhFBsbyW28yF/WiaB8iahGzUYVWK32ys4o+uOfL3sSMQ6kCAwEAAQ==
      initial-size: 20
      min-idle: 20
      max-active: 50
      max-wait: 60000
      test-while-idle: true
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select *
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: false
      filters: stat,wall,slf4j
      connect-properties:
        druid.stat.mergeSql: true
        druid.stat.slowSqlMills: 5000
      time-between-log-stats-millis: 300000
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: '/druid/*'
        allow:  127.0.0.1
        reset-enable: false
        login-username: bsAdmin
        login-password: 123qwe
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis.xml
  type-aliases-package: com.cardinal.tech.bean.dbo

